### ISSUE TITLE
Timeout if send_frame is called within a handle_frame

### ISSUE THREAD

**Issue by leordev** [Azolo/websockex#47] opened 2017-12-31 18:32 UTC
First of all thanks for the library, it works great from phoenix as a client!

It's probably a newbie question that I'm missing something in how to use the library.

But I have this code:

```
def handle_frame({:text, "#" <> pingNum}, state) do
    Logger.info("Coinigy Ping ##{pingNum} Received")

    WebSockex.send_frame(self(), {:text, "##{String.to_integer(pingNum) + 1}"})

    {:ok, state}
  end
```

And I get timeout because it looks like the send_frame is not being sent to the server... This is what I receive on my terminate function:

```
{:timeout, {WebSockex, :call, [#PID<0.336.0>, {:text, "#2"}]}}
```

So my workaround is to use one of my servers (GenServer) to listen to whatever message is being sent or received from my WebSockex. Is there any better approach for that? Why can't I call send_frame from a handle_frame?

**Comment by Azolo** [comment] 2017-12-31 19:43
This is a duplicate of #34

I'll get better documentation in the README

**Closed by Azolo** 2017-12-31 19:43 UTC
Labels: duplicate
